500px:
  - changed-files:
      - any-glob-to-any-file: 500px/**
duolingo:
  - changed-files:
      - any-glob-to-any-file: duolingo/**
internal:
  - changed-files:
      - any-glob-to-any-file: internal/**
lonely-planet:
  - changed-files:
      - any-glob-to-any-file: lonely-planet/**
photos:
  - changed-files:
      - any-glob-to-any-file: photos/**
