name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: denoland/setup-deno@v2

      - name: Test
        run: deno task ok

      - name: Build
        run: deno task build

      - name: Publish (dry-run)
        run: deno publish --dry-run

  publish:
    if: github.ref == 'refs/heads/main'
    needs: build

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: denoland/setup-deno@v2

      - name: Publish
        run: deno publish
