name: Release

on: workflow_dispatch

jobs:
  build:
    name: version bump
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup
        uses: denoland/setup-deno@v2

      - name: Bump versions
        run: deno run -A jsr:@deno/bump-workspaces@^0.1.22/cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
